#ifndef INCLUDE_COMMON_H
#define INCLUDE_COMMON_H

#include <SDL3/SDL.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <stdlib.h>
#include <stdio.h>

// Render
#define RENDER_PIXEL_FORMAT SDL_PIXELFORMAT_RGBA32
#define RENDER_BLENDMODE SDL_BLENDMODE_BLEND

// Color
#define COLOR_ZERO (SDL_Color){ 0, 0, 0, 0 }
#define COLOR_ZERO_FLOAT (SDL_FColor){ 0.0f, 0.0f, 0.0f, 0.0f }
#define COLOR_WHITE (SDL_Color){ 255, 255, 255, 255 }
#define COLOR_TRANSLUCENT_BLACK (SDL_Color){ 0, 0, 0, 127 }
#define COLOR_BLACK (SDL_Color){ 0, 0, 0, 255 }

// Texture
#define TEXTURE_START 0
#define TEXTURE_END 1

// Window
#define WINDOW_NAME "Point Game"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_MAX_FPS 60.0f
#define WINDOW_DELTA_TIME (1000.0f / WINDOW_MAX_FPS)
#define WINDOW_SCALE 64.0f
#define WINDOW_WIDTH_SCALE (WINDOW_WIDTH / WINDOW_SCALE)
#define WINDOW_HEIGHT_SCALE (WINDOW_HEIGHT / WINDOW_SCALE)
#define WINDOW_FONT_PATH "./sources/fusion-pixel-10px-monospaced-zh_hans.ttf"

// Player
#define PLAYER_DEFAULT_DIRECTION 0.0f
#define PLAYER_SIZE 1.0f
#define PLAYER_SIZE_HALF (PLAYER_SIZE / 2.0f)
#define PLAYER_COLOR (SDL_Color){ 0, 255, 0, 255 }
#define PLAYER_MOVE_SPEED 5.0f
#define PLAYER_SIGHT_FOV (SDL_PI_F * 0.5f)
#define PLAYER_SIGHT_FOV_HALF (PLAYER_SIGHT_FOV / 2.0f)
#define PLAYER_SIGHT_RAY_NUMBER 100
#define PLAYER_SIGHT_RAY_DELTA (PLAYER_SIGHT_FOV / PLAYER_SIGHT_RAY_NUMBER)

// Player texture
#define PLAYER_TEXTURE_FILE "./sources/player.png"
#define PLAYER_TEXTURE_SIZE 48
#define PLAYER_TEXTURE_EDGE ((SDL_Rect){ 14, 20, 21, 25 })
#define PLAYER_TEXTURE_CHANGE_DELTA_TIME_MS 100
#define PLAYER_TEXTURE_COLUMNS 6
#define PLAYER_TEXTURE_ROWS 10
#define PLAYER_TEXTURE_ROW_IDLE ((Uint8[]){ 0, 2 })
#define PLAYER_TEXTURE_ROW_MOVE ((Uint8[]){ 3, 5 })

// Map
#define MAP_FILE "./sources/map.txt"
#define MAP_TEXTURE_FILE "./sources/map.png"
#define MAP_TEXTURE_SIZE 16
#define MAP_TEXTURE_WALL_HEIGHT 24
#define MAP_TEXTURE_FLOOR (SDL_Point){ 4, 3 }
#define MAP_TEXTURE_WALL (SDL_Point){ 8, 1 }
#define MAP_WALL_DELTA_SCALE \
	((float)(MAP_TEXTURE_WALL_HEIGHT - MAP_TEXTURE_SIZE) / MAP_TEXTURE_SIZE)
#define MAP_WALL_DELTA (MAP_WALL_DELTA_SCALE * WINDOW_SCALE)

// Bullet
#define BULLET_WIDTH 0.2f
#define BULLET_HEIGHT 0.08f
#define BULLET_COLOR (SDL_Color){ 255, 255, 0, 255 }
#define BULLET_SPEED 10.0f
#define BULLET_SHOOT_DELTA 100.0f
#define BULLET_MAX_COUNT 30
#define BULLET_RELOAD_TIME_MS 1000.0f

// UI
#define UI_DEFAULT_EDGE_COLOR COLOR_WHITE
#define UI_DEFAULT_BG_COLOR COLOR_ZERO
#define UI_DEFAULT_FONT_COLOR COLOR_WHITE
#define UI_DEFAULT_FONT_SIZE WINDOW_SCALE

#define UI_INFOLABEL_FONT_SIZE (WINDOW_SCALE * 0.8f)

#define UI_MENU_BUTTON_POS \
	(SDL_FPoint){ WINDOW_WIDTH_SCALE / 2.0f, WINDOW_HEIGHT_SCALE / 2.0f }

#define UI_START_TITLE_POS (SDL_FPoint){ WINDOW_WIDTH_SCALE / 2.0f, 2.0f }
#define UI_START_BUTTON_POS (SDL_FPoint){ WINDOW_WIDTH_SCALE / 2.0f, 6.0f }

#endif /* INCLUDE_COMMON_H */